spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/tareas_bd 
spring.datasource.username=postgres
spring.datasource.password=caborico
spring.jpa.hibernate.ddl-auto=update